server:
  port: 9090

spring:
  application:
    name: canteen-manage
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/canteen_manage
    username: root
    password: lvbohan2003
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

fileBaseUrl: http://localhost:${server.port}