ALTER TABLE admin
ADD COLUMN password_hash VARCHAR(255) NOT NULL,
ADD COLUMN salt VARCHAR(255) NOT NULL;

ALTER TABLE student
ADD COLUMN password_hash VARCHAR(255) NOT NULL,
ADD COLUMN salt VARCHAR(255) NOT NULL;